### ISSUE TITLE
Day two peer to peer code review

### ISSUE THREAD

**Issue by mohamedgamaleldin999999** [migo1/portfolio#11]
we opened this issue following the activity for day two week four

**Comment by mohamedgamaleldin999999** [comment]
the code looks fine to me. no changes recquired

**Comment by lily4178993** [comment]
Good job so far.

**Comment by mohamedgamaleldin999999** [comment]
Agreed on approval

**Comment by roshanasingh4** [comment]
I don't know for sure if it's an issue or not but the **I'm** part before the name **Migot** appears when the screen is set to 770px and also the social icons overflow. Let me know what you guys think.

**P.s. I don't know if that's the exact design or an issue, since I used template 3.**

![image](https://github.com/migo1/portfolio/assets/88576930/92631eb2-8fb8-4716-a894-0322883e25c7)

With the dev tools 

![Uploading image.png…]()
